#!/usr/bin/env node
/* ==========================================================================
   manifest.mjs — regenerate sw-precache.js, the list of files the service
   worker stores for offline use, plus a version stamp derived from their
   contents so the cache invalidates itself when anything changes.

   Run: node tools/manifest.mjs           writes sw-precache.js
        node tools/manifest.mjs --check   exits 1 if it is out of date

   This is not a build step for the page — nothing here runs in a browser and
   the site works without it. It exists so the precache list is never
   hand-maintained, because a hand-maintained list is a list that silently
   stops matching the site.
   ========================================================================== */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { createHash } from "node:crypto";
import { ROOT, tripSlugs } from "./lib/site.mjs";

const CHECK = process.argv.includes("--check");
const OUT = join(ROOT, "sw-precache.js");

/* Everything the site needs to open with no network. Order is cosmetic. */
function assetList() {
  const files = [
    "index.html",
    "css/base.css",
    "css/hub.css",
    "css/trip.css",
    "css/print.css",
    "js/themes.js",
    "js/derive.js",
    "js/exports.js",
    "js/ui.js",
    "js/offline.js",
    "js/hub.js",
    "js/trip.js",
    "data/profile.js",
    "data/trips.js",
    "vendor/leaflet/leaflet.css",
    "vendor/leaflet/leaflet.js",
    "vendor/leaflet/images/layers.png",
    "vendor/leaflet/images/layers-2x.png",
    "vendor/leaflet/images/marker-icon.png",
    "vendor/leaflet/images/marker-icon-2x.png",
    "vendor/leaflet/images/marker-shadow.png",
  ];
  for (const slug of tripSlugs()) {
    files.push(`trips/${slug}/index.html`, `trips/${slug}/data.js`);
  }
  return files;
}

const files = assetList();
const missing = files.filter((f) => !existsSync(join(ROOT, f)));
if (missing.length) {
  console.log("  FAIL  manifest lists files that do not exist:");
  for (const m of missing) console.log(`          ${m}`);
  process.exit(1);
}

/* Version = hash of every byte the service worker will store. Change any of
   them and the cache name changes, so the old cache is dropped on activate. */
const hash = createHash("sha256");
for (const f of files) {
  hash.update(f);
  hash.update(readFileSync(join(ROOT, f)));
}
const version = hash.digest("hex").slice(0, 12);

const body = `/* GENERATED by tools/manifest.mjs — do not edit by hand.
   Regenerate with: node tools/manifest.mjs
   The version is a hash of every listed file, so editing any of them changes
   the cache name and retires the old cache automatically. */

self.PRECACHE_VERSION = "${version}";
self.PRECACHE_FILES = [
${files.map((f) => `  "${f}",`).join("\n")}
];
`;

const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";

if (CHECK) {
  if (current !== body) {
    console.log("  FAIL  sw-precache.js is out of date — run: node tools/manifest.mjs");
    process.exit(1);
  }
  console.log(`sw-precache.js is current (${files.length} files, ${version})`);
  process.exit(0);
}

if (current === body) {
  console.log(`sw-precache.js unchanged (${files.length} files, ${version})`);
} else {
  writeFileSync(OUT, body);
  console.log(`sw-precache.js written — ${files.length} files, version ${version}`);
}
